name: Deploy APP Alliance Admin

on: 
  push: 
    branches: [main]
  merge_group: 
    branches: [main]
  workflow_dispatch:

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies 
        run: npm install --force

      - name: Build project
        run: npm run build  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: "./"
          push: true
          tags: adrsilva01/works:alliance-app-admin
  
  deploy:
    runs-on: ubuntu-latest
    name: Deploy application
    needs: build
    steps:
      - name: Access VPS
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{vars.REMOTE_HOST}}
          password: ${{secrets.REMOTE_PASS}}
          username: ${{vars.REMOTE_USER}}            
          script: |
            cd /home/ubuntu 
            docker stop app 
            docker rm app 
            docker pull adrsilva01/works:alliance-app-admin 
            docker run --name app --restart=always -d -p${{vars.PORT_APP}}:${{vars.PORT_APP}} --env API_BASE_URL=${{vars.NEXT_PUBLIC_BASE_HOST}} --env NEXT_PUBLIC_API_URL=${{vars.NEXT_PUBLIC_BASE_HOST}} --env NODE_ENV=production adrsilva01/works:alliance-app-admin